### ISSUE TITLE
2 of 3 request error 500

### ISSUE THREAD

**Issue by borissov** [tommienu/zf2appengine#1]
Hello,
I install zend framework on GAE, but have some problems..
2 of 3 request are with error 500.
I only found warning:
A problem was encountered with the process that handled this request, causing it to exit. This is likely to cause a new process to be used for the next request to your application. (Error code 204)
How can I fix this?

**Comment by euphio** [comment]
I have just put in a PR with a fix for this: https://github.com/tommienu/zf2appengine/pull/2

It's an APC bug in GAE.

**Comment by borissov** [comment]
Solved. Thanks a lot.
